# Generated by Django 5.1.6 on 2025-02-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buy4me", "0002_alter_buy4meitem_id_alter_buy4merequest_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buy4meitem",
            name="id",
            field=models.CharField(
                editable=False, max_length=12, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="buy4merequest",
            name="id",
            field=models.CharField(
                editable=False, max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
