# Generated by Django 5.1.6 on 2025-02-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buy4me", "0003_alter_buy4meitem_id_alter_buy4merequest_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="buy4meitem",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
