# Generated by Django 5.1.6 on 2025-02-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buy4me", "0004_buy4meitem_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buy4merequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("ORDER_PLACED", "Order Placed"),
                    ("IN_TRANSIT", "In Transit"),
                    ("WAREHOUSE_ARRIVED", "Warehouse Arrived"),
                    ("SHIPPED_TO_CUSTOMER", "Shipped to Customer"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
