# Generated by Django 5.1.6 on 2025-02-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buy4me", "0005_alter_buy4merequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="buy4merequest",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("REFUNDED", "Refunded"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
