# Generated by Django 5.1.6 on 2025-03-07 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buy4me", "0007_buy4merequest_staff"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="buy4merequest",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                help_text="Driver assigned to deliver this request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driver_buy4me_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="buy4merequest",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member assigned to handle this request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_buy4me_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
