# Generated by Django 5.1.6 on 2025-03-12 05:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_city_remove_driverprofile_commission_rate_and_more"),
        ("buy4me", "0008_buy4merequest_driver_alter_buy4merequest_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="buy4merequest",
            name="city",
            field=models.ForeignKey(
                blank=True,
                help_text="City for delivery, determines delivery charge and assigned driver",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buy4me_requests",
                to="accounts.city",
            ),
        ),
        migrations.AddField(
            model_name="buy4merequest",
            name="delivery_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Fixed delivery charge based on city",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
