# Generated by Django 5.0.2 on 2025-03-30 09:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buy4me", "0009_buy4merequest_city_buy4merequest_delivery_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="buy4merequest",
            name="shipping_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
