# Generated by Django 5.0.2 on 2025-03-30 09:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buy4me", "0010_buy4merequest_shipping_cost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buy4merequest",
            name="delivery_charge",
        ),
        migrations.RemoveField(
            model_name="buy4merequest",
            name="shipping_cost",
        ),
        migrations.AddField(
            model_name="buy4meitem",
            name="store_to_warehouse_delivery_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Delivery charge from store to our warehouse",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="buy4merequest",
            name="city_delivery_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Delivery charge from warehouse to customer city",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
