# Generated by Django 5.0.2 on 2025-03-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buy4me", "0011_remove_buy4merequest_delivery_charge_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buy4meitem",
            name="product_url",
            field=models.URLField(max_length=1000),
        ),
    ]
