# Generated by Django 5.0.2 on 2025-04-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buy4me", "0013_buy4medriverpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buy4merequest",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("COD", "COD"),
                    ("COD_PAID", "COD Paid"),
                    ("REFUNDED", "Refunded"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Buy4MeDriverPayment",
        ),
    ]
