# Generated by Django 5.0.2 on 2025-04-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buy4me", "0014_alter_buy4merequest_payment_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buy4merequest",
            name="city",
        ),
        migrations.RemoveField(
            model_name="buy4merequest",
            name="city_delivery_charge",
        ),
    ]
