# Generated by Django 5.0.2 on 2025-04-12 03:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buy4me", "0015_remove_buy4merequest_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buy4merequest",
            name="service_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
