# Generated by Django 5.1.6 on 2025-02-17 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shipments",
            "0004_rename_content_description_shipmentrequest_recipient_address_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipmentrequest",
            name="dimensions",
        ),
        migrations.AddField(
            model_name="shipmentrequest",
            name="height",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipmentrequest",
            name="length",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipmentrequest",
            name="width",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
    ]
