# Generated by Django 5.1.6 on 2025-02-17 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0005_remove_shipmentrequest_dimensions_and_more"),
        ("shipping_rates", "0005_country_unique_country_code_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipmentrequest",
            name="recipient_country",
            field=models.ForeignKey(
                limit_choices_to={"country_type": "DESTINATION"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments_as_recipient",
                to="shipping_rates.country",
            ),
        ),
        migrations.AlterField(
            model_name="shipmentrequest",
            name="sender_country",
            field=models.ForeignKey(
                limit_choices_to={"country_type": "DEPARTURE"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments_as_sender",
                to="shipping_rates.country",
            ),
        ),
        migrations.AlterField(
            model_name="shipmentrequest",
            name="service_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments",
                to="shipping_rates.servicetype",
            ),
        ),
    ]
