# Generated by Django 5.1.6 on 2025-02-17 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0006_alter_shipmentrequest_recipient_country_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shipmentrequest",
            old_name="cost",
            new_name="base_rate",
        ),
        migrations.RemoveField(
            model_name="shipmentrequest",
            name="insurance_cost",
        ),
        migrations.AddField(
            model_name="shipmentrequest",
            name="per_kg_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=23,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipmentrequest",
            name="total_additional_charges",
            field=models.DecimalField(
                decimal_places=2,
                default=32,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipmentrequest",
            name="weight_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=3,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
    ]
