# Generated by Django 5.1.6 on 2025-02-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0007_rename_cost_shipmentrequest_base_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentrequest",
            name="current_location",
            field=models.CharField(
                blank=True, help_text="Current location of the shipment", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="shipmentrequest",
            name="estimated_delivery",
            field=models.DateTimeField(
                blank=True, help_text="Estimated delivery date and time", null=True
            ),
        ),
        migrations.AddField(
            model_name="shipmentrequest",
            name="tracking_history",
            field=models.JSONField(
                default=list,
                help_text="List of tracking updates with timestamp and location",
            ),
        ),
        migrations.AlterField(
            model_name="shipmentrequest",
            name="tracking_number",
            field=models.CharField(
                db_index=True,
                default=2323,
                help_text="Unique tracking number for the shipment",
                max_length=50,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
