# Generated by Django 5.1.6 on 2025-02-17 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0008_shipmentrequest_current_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentrequest",
            name="service_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=50,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
    ]
