# Generated by Django 5.1.6 on 2025-02-24 11:10

import shipments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0009_shipmentrequest_service_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentrequest",
            name="receipt",
            field=models.FileField(
                blank=True,
                help_text="PDF receipt for the shipment",
                null=True,
                upload_to=shipments.models.shipment_receipt_path,
            ),
        ),
    ]
