# Generated by Django 5.1.6 on 2025-03-02 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0010_shipmentrequest_receipt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentrequest",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member assigned to handle this shipment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_shipments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="ShipmentTracking",
        ),
    ]
