# Generated by Django 5.1.6 on 2025-03-03 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0011_shipmentrequest_staff_delete_shipmenttracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentrequest",
            name="cod_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Additional amount for Cash on Delivery (5% of total cost)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="shipmentrequest",
            name="payment_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when payment was completed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shipmentrequest",
            name="payment_method",
            field=models.CharField(
                choices=[("ONLINE", "Online Payment"), ("COD", "Cash on Delivery")],
                default="ONLINE",
                help_text="Method of payment for the shipment",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="shipmentrequest",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                help_text="Current status of the payment",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="shipmentrequest",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                help_text="Payment transaction ID from payment processor",
                max_length=100,
            ),
        ),
    ]
