# Generated by Django 5.1.6 on 2025-03-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0012_shipmentrequest_cod_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipmentStatusLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_type",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("PICKED_UP", "Picked Up"),
                            ("IN_TRANSIT", "In Transit"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        help_text="Type of status transition",
                        max_length=20,
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        help_text="Location name to use for this status", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description to use for this status update"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this status location is active"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order to display in admin actions"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shipment Status Location",
                "verbose_name_plural": "Shipment Status Locations",
                "ordering": ["display_order", "status_type"],
                "unique_together": {("status_type", "location_name")},
            },
        ),
    ]
