# Generated by Django 5.1.6 on 2025-03-05 10:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0013_add_default_status_locations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(
                        editable=False,
                        help_text="Unique ticket identifier",
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Brief description of the issue", max_length=255
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Detailed description of the issue"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SHIPPING", "Shipping Issue"),
                            ("PAYMENT", "Payment Issue"),
                            ("TRACKING", "Tracking Issue"),
                            ("DELIVERY", "Delivery Issue"),
                            ("PICKUP", "Pickup Issue"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Category of the support ticket",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        help_text="Current status of the ticket",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Priority level (1-5)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When the ticket was resolved", null=True
                    ),
                ),
                (
                    "response_time",
                    models.DurationField(
                        blank=True, help_text="Time taken for first response", null=True
                    ),
                ),
                (
                    "resolution_time",
                    models.DurationField(
                        blank=True,
                        help_text="Time taken to resolve the ticket",
                        null=True,
                    ),
                ),
                (
                    "communication_history",
                    models.JSONField(
                        default=list,
                        help_text="History of all communications on this ticket",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member assigned to handle this ticket",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related shipment if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_tickets",
                        to="shipments.shipmentrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created the ticket",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ticket_number"], name="shipments_s_ticket__9748db_idx"
                    ),
                    models.Index(
                        fields=["status"], name="shipments_s_status_1aaf17_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="shipments_s_created_980548_idx"
                    ),
                ],
            },
        ),
    ]
