# Generated by Django 5.1.6 on 2025-03-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0014_supportticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supportticket",
            name="communication_history",
        ),
        migrations.RemoveField(
            model_name="supportticket",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="supportticket",
            name="resolution_time",
        ),
        migrations.RemoveField(
            model_name="supportticket",
            name="response_time",
        ),
        migrations.AddField(
            model_name="supportticket",
            name="comments",
            field=models.JSONField(
                default=list, help_text="List of comments on this ticket"
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("SHIPPING", "Shipping Issue"),
                    ("PAYMENT", "Payment Issue"),
                    ("TRACKING", "Tracking Issue"),
                    ("DELIVERY", "Delivery Issue"),
                    ("OTHER", "Other"),
                ],
                help_text="Category of the support ticket",
                max_length=20,
            ),
        ),
    ]
