# Generated by Django 5.1.6 on 2025-03-07 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0015_remove_supportticket_communication_history_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentrequest",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                help_text="Driver assigned to deliver this shipment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driver_shipments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
