# Generated by Django 5.0.2 on 2025-03-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0017_shipmentrequest_city_shipmentrequest_delivery_charge"),
        ("shipping_rates", "0012_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentrequest",
            name="extras",
            field=models.ManyToManyField(blank=True, to="shipping_rates.extras"),
        ),
    ]
