# Generated by Django 5.0.2 on 2025-03-21 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0018_shipmentrequest_extras"),
        ("shipping_rates", "0013_remove_weightbasedrate_regulation_charge"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipmentExtras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "extra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shipping_rates.extras",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shipments.shipmentrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment Extra",
                "verbose_name_plural": "Shipment Extras",
                "unique_together": {("shipment", "extra")},
            },
        ),
    ]
