# Generated by Django 5.0.2 on 2025-03-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0019_shipmentextras"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipmentrequest",
            name="extras",
        ),
    ]
