# Generated by Django 5.0.2 on 2025-03-21 16:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0020_remove_shipmentrequest_extras"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentrequest",
            name="extras_charges",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total charges from extras/additional services",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
