# Generated by Django 5.0.2 on 2025-03-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0021_shipmentrequest_extras_charges"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipmentrequest",
            name="extras_charges",
        ),
    ]
