# Generated by Django 5.0.2 on 2025-03-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0023_shipmentrequest_extras_charges"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipmentMessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("confirmation", "Shipment Confirmation"),
                            ("notification", "Shipment Notification"),
                            ("delivery", "Delivery Notification"),
                            ("custom", "Custom Message"),
                        ],
                        help_text="Type of message template",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Subject line for email communications",
                        max_length=200,
                    ),
                ),
                (
                    "message_content",
                    models.TextField(
                        help_text="Message template with placeholders. Available placeholders: {recipient_name}, {sender_name}, {sender_country}, {tracking_number}, {package_type}, {weight}, {dimensions}, {status}, {current_location}, {estimated_delivery}, {description}, {sender_email}, {sender_phone}"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this template is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shipment Message Template",
                "verbose_name_plural": "Shipment Message Templates",
                "ordering": ["template_type"],
            },
        ),
    ]
