# Generated by Django 5.0.2 on 2025-03-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0024_shipmentmessagetemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipmentmessagetemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("confirmation", "Shipment Confirmation"),
                    ("notification", "Shipment Notification"),
                    ("delivery", "Delivery Notification"),
                    ("sender_notification", "Sender Notification"),
                    ("custom", "Custom Message"),
                ],
                help_text="Type of message template",
                max_length=20,
                unique=True,
            ),
        ),
    ]
