# Generated by Django 5.0.2 on 2025-03-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0025_alter_shipmentmessagetemplate_template_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipmentstatuslocation",
            name="status_type",
            field=models.CharField(
                help_text="Status type for this location", max_length=50
            ),
        ),
    ]
