# Generated by Django 5.0.2 on 2025-03-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0026_alter_shipmentstatuslocation_status_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipmentstatuslocation",
            name="status_type",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("PICKED_UP", "Picked Up"),
                    ("IN_TRANSIT", "In Transit"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                help_text="Type of status transition",
                max_length=20,
            ),
        ),
    ]
