# Generated by Django 5.0.2 on 2025-03-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0027_alter_shipmentstatuslocation_status_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipmentrequest",
            name="recipient_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="shipmentrequest",
            name="sender_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
