# Generated by Django 5.0.2 on 2025-03-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0028_alter_shipmentrequest_recipient_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipmentrequest",
            name="base_rate",
        ),
        migrations.RemoveField(
            model_name="shipmentrequest",
            name="service_charge",
        ),
    ]
