# Generated by Django 5.0.2 on 2025-03-29 10:19

import shipments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0029_remove_shipmentrequest_base_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentrequest",
            name="awb",
            field=models.FileField(
                blank=True,
                help_text="PDF file of the Air Waybill",
                null=True,
                upload_to=shipments.models.shipment_awb_path,
            ),
        ),
    ]
