# Generated by Django 5.0.2 on 2025-03-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0031_supportticket_admin_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipmentrequest",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("COD_PENDING", "COD Pending"),
                    ("COD_PAID", "COD Paid"),
                    ("FAILED", "Failed"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                help_text="Current status of the payment",
                max_length=20,
            ),
        ),
    ]
