# Generated by Django 5.0.2 on 2025-04-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0032_alter_shipmentrequest_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipmentrequest",
            name="declared_value",
            field=models.CharField(
                help_text="Declared value for customs", max_length=255
            ),
        ),
    ]
