# Generated by Django 5.0.2 on 2025-04-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0033_alter_shipmentrequest_declared_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipmentmessagetemplate",
            name="message_content",
            field=models.TextField(
                help_text="Message template with placeholders. Available placeholders: {recipient_name}, {sender_name}, {sender_country}, {tracking_number}, {package_type}, {weight}, {dimensions}, {status}, {current_location}, {estimated_delivery}, {description}, {sender_email}, {sender_phone}, {total_cost}, {converted_cost}"
            ),
        ),
    ]
