# Generated by Django 5.0.2 on 2025-04-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0034_alter_shipmentmessagetemplate_message_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipmentrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("IN_TRANSIT", "In Transit"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("FAILED_DELIVERY", "Failed Delivery"),
                    ("RETURNED", "Returned"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
