# Generated by Django 5.0.2 on 2025-04-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0035_alter_shipmentrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentrequest",
            name="no_of_packages",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of packages in the shipment"
            ),
        ),
        migrations.AlterField(
            model_name="shipmentstatuslocation",
            name="status_type",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("PICKED_UP", "Picked Up"),
                    ("IN_TRANSIT", "In Transit"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("FAILED_DELIVERY", "Failed Delivery"),
                    ("RETURNED", "Returned"),
                ],
                help_text="Type of status transition",
                max_length=20,
            ),
        ),
    ]
