# Generated by Django 5.0.2 on 2025-04-22 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0036_shipmentrequest_no_of_packages_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipmentrequest",
            name="no_of_packages",
            field=models.IntegerField(
                default=1, help_text="Number of packages in the shipment"
            ),
        ),
        migrations.CreateModel(
            name="ShipmentPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_type", models.CharField(max_length=50)),
                ("number", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("FAILED_DELIVERY", "Failed Delivery"),
                            ("RETURNED", "Returned"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "tracking_history",
                    models.JSONField(
                        default=list,
                        help_text="List of tracking updates with timestamp and location",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="shipments.shipmentrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
