# Generated by Django 5.0.2 on 2025-04-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0037_alter_shipmentrequest_no_of_packages_shipmentpackage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shipmentpackage",
            options={},
        ),
    ]
