# Generated by Django 5.1.6 on 2025-02-18 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_default_shipping_method_user_preferred_currency"),
        ("shipping_rates", "0006_servicetype_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shipping_rates.country",
            ),
        ),
    ]
