# Generated by Django 5.1.6 on 2025-02-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="preferred_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("GBP", "GBP"),
                    ("CAD", "CAD"),
                    ("AUD", "AUD"),
                ],
                default="USD",
                max_length=10,
            ),
        ),
    ]
