# Generated by Django 5.1.6 on 2025-02-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_store"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="domains",
        ),
        migrations.AddField(
            model_name="store",
            name="url",
            field=models.URLField(default="https://google.com", unique=True),
            preserve_default=False,
        ),
    ]
