# Generated by Django 5.1.6 on 2025-03-06 06:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("WALK_IN", "Walk In"),
                    ("BUY4ME", "Buy4Me"),
                    ("DRIVER", "Driver"),
                    ("ADMIN", "Admin"),
                    ("SUPER_ADMIN", "Super Admin"),
                ],
                default="WALK_IN",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=12, primary_key=True, serialize=False
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("MOTORCYCLE", "Motorcycle"),
                            ("CAR", "Car"),
                            ("VAN", "Van"),
                            ("TRUCK", "Truck"),
                        ],
                        default="CAR",
                        help_text="Type of vehicle used for deliveries",
                        max_length=20,
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        help_text="Driver's license number", max_length=50
                    ),
                ),
                (
                    "vehicle_plate",
                    models.CharField(
                        help_text="Vehicle license plate number", max_length=20
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this driver is currently active",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Commission percentage for completed deliveries",
                        max_digits=5,
                    ),
                ),
                (
                    "total_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total earnings from commissions",
                        max_digits=10,
                    ),
                ),
                (
                    "total_deliveries",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of completed deliveries"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Driver user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Profile",
                "verbose_name_plural": "Driver Profiles",
            },
        ),
        migrations.CreateModel(
            name="DeliveryCommission",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=12, primary_key=True, serialize=False
                    ),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[("SHIPMENT", "Shipment"), ("BUY4ME", "Buy4Me")],
                        help_text="Type of delivery",
                        max_length=20,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        help_text="ID of the related shipment or buy4me request",
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Commission amount", max_digits=10
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the commission was earned"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description of the commission",
                        max_length=255,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        help_text="Driver who earned the commission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="accounts.driverprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Commission",
                "verbose_name_plural": "Delivery Commissions",
                "ordering": ["-earned_at"],
            },
        ),
    ]
