# Generated by Django 5.1.6 on 2025-03-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_user_user_type_driverprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
