# Generated by Django 5.1.6 on 2025-03-07 10:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_store_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driverprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Driver Profile",
                "verbose_name_plural": "Driver Profiles",
            },
        ),
        migrations.RemoveField(
            model_name="driverprofile",
            name="vehicle_plate",
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                help_text="Commission rate as a percentage",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this driver is active and available for deliveries",
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="total_earnings",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total earnings from all deliveries",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="user",
            field=models.OneToOneField(
                help_text="User account associated with this driver profile",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="vehicle_type",
            field=models.CharField(
                help_text="Type of vehicle used by the driver", max_length=50
            ),
        ),
    ]
