# Generated by Django 5.1.6 on 2025-03-12 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_driverprofile_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=12, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the city", max_length=100),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        help_text="Postal code (optional)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "delivery_charge",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fixed delivery charge for this city",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this city is active for deliveries",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="driverprofile",
            name="commission_rate",
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="cities",
            field=models.ManyToManyField(
                blank=True,
                help_text="Cities this driver is assigned to",
                related_name="drivers",
                to="accounts.city",
            ),
        ),
    ]
