# Generated by Django 5.1.6 on 2025-03-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.PositiveIntegerField(blank=True, max_length=15, unique=True),
        ),
    ]
