# Generated by Django 5.1.6 on 2025-03-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.PositiveIntegerField(blank=True, unique=True),
        ),
    ]
