# Generated by Django 5.0.2 on 2025-03-20 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_alter_user_email"),
        ("buy4me", "0009_buy4merequest_city_buy4merequest_delivery_charge"),
        ("shipments", "0018_shipmentrequest_extras"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverPayment",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=12, primary_key=True, serialize=False
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount of the payment",
                        max_digits=10,
                    ),
                ),
                (
                    "payment_for",
                    models.CharField(
                        choices=[("SHIPMENT", "Shipment"), ("BUY4ME", "Buy4Me")],
                        default="SHIPMENT",
                        help_text="Payment for",
                        max_length=50,
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date and time of the payment"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buy4me",
                    models.ForeignKey(
                        blank=True,
                        help_text="Buy4Me request for which the payment is made",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_payments",
                        to="buy4me.buy4merequest",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        help_text="Driver who Done the payment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shipment for which the payment is made",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_payments",
                        to="shipments.shipmentrequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
