# Generated by Django 5.0.2 on 2025-03-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_driverpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverpayment",
            name="payment_id",
            field=models.CharField(
                default="asdl", help_text="Payment ID", max_length=50
            ),
            preserve_default=False,
        ),
    ]
