# Generated by Django 5.0.2 on 2025-03-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_driverpayment_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="plain_password",
            field=models.CharField(
                blank=True,
                help_text="Plain text password for message generation",
                max_length=128,
                null=True,
            ),
        ),
    ]
