# Generated by Django 5.0.2 on 2025-03-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_user_plain_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="plain_password",
            field=models.CharField(
                blank=True,
                help_text="Encrypted password for message generation",
                max_length=255,
                null=True,
            ),
        ),
    ]
