# Generated by Django 5.0.2 on 2025-04-03 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_alter_user_plain_password"),
        ("shipping_rates", "0013_remove_weightbasedrate_regulation_charge"),
    ]

    operations = [
        # 1. Add a temporary nullable field for the foreign key
        migrations.AddField(
            model_name="user",
            name="preferred_currency_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shipping_rates.currency",
            ),
        ),
        
        # 2. Create an empty column for preferred_currency to move it away
        migrations.RunSQL(
            "ALTER TABLE accounts_user RENAME COLUMN preferred_currency TO preferred_currency_old",
            reverse_sql="ALTER TABLE accounts_user RENAME COLUMN preferred_currency_old TO preferred_currency",
        ),
        
        # 3. Create preferred_currency field as the new foreign key column
        migrations.RunSQL(
            "ALTER TABLE accounts_user RENAME COLUMN preferred_currency_fk_id TO preferred_currency_id",
            reverse_sql="ALTER TABLE accounts_user RENAME COLUMN preferred_currency_id TO preferred_currency_fk_id",
        ),
    ]
