# Generated by Django 5.0.2 on 2025-04-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_alter_user_preferred_currency"),
    ]

    operations = [
        # Just clean up by dropping the old column
        migrations.RunSQL(
            "ALTER TABLE accounts_user DROP COLUMN preferred_currency_old",
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
