# Generated by Django 5.0.2 on 2025-04-03 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_migrate_currency_values"),
        ("shipping_rates", "0013_remove_weightbasedrate_regulation_charge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="preferred_currency_fk",
        ),
        migrations.AlterField(
            model_name="user",
            name="preferred_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shipping_rates.currency",
            ),
        ),
    ]
