# Generated by Django 5.0.2 on 2025-04-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_add_currency_fk_field"),
    ]

    operations = [
        # SQLite doesn't support direct column dropping - we need to create a new table and copy data
        migrations.RunSQL(
            sql="""
            PRAGMA foreign_keys=off;
            
            -- Create a new table without the old column
            CREATE TABLE accounts_user_new (
                id VARCHAR(12) NOT NULL PRIMARY KEY,
                password VARCHAR(128) NOT NULL,
                last_login DATETIME NULL,
                is_superuser BOOL NOT NULL,
                username VARCHAR(150) NOT NULL UNIQUE,
                first_name VARCHAR(150) NOT NULL,
                last_name VARCHAR(150) NOT NULL,
                is_staff BOOL NOT NULL,
                is_active BOOL NOT NULL,
                date_joined DATETIME NOT NULL,
                email VARCHAR(254) NULL,
                user_type VARCHAR(20) NOT NULL,
                phone_number VARCHAR(15) NULL UNIQUE,
                address TEXT NOT NULL,
                is_verified BOOL NOT NULL,
                plain_password VARCHAR(255) NULL,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NOT NULL,
                country_id VARCHAR(12) NULL REFERENCES accounts_usercountry (id) ON DELETE SET NULL,
                default_shipping_method_id INTEGER NULL REFERENCES shipping_rates_servicetype (id) ON DELETE SET NULL,
                preferred_currency_id INTEGER NULL REFERENCES shipping_rates_currency (id) ON DELETE SET NULL
            );
            
            -- Copy data from old table to new table
            INSERT INTO accounts_user_new 
            SELECT 
                id, password, last_login, is_superuser, username, first_name, last_name,
                is_staff, is_active, date_joined, email, user_type, phone_number, address, 
                is_verified, plain_password, created_at, updated_at, country_id, 
                default_shipping_method_id, preferred_currency_id
            FROM accounts_user;
            
            -- Drop old table and rename new one
            DROP TABLE accounts_user;
            ALTER TABLE accounts_user_new RENAME TO accounts_user;
            
            -- Recreate indices
            CREATE INDEX accounts_user_country_id_e3a9c70f ON accounts_user (country_id);
            CREATE INDEX accounts_user_default_shipping_method_id_32d1ab89 ON accounts_user (default_shipping_method_id);
            CREATE INDEX accounts_user_preferred_currency_id ON accounts_user (preferred_currency_id);
            
            PRAGMA foreign_keys=on;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
