# Generated by Django 5.0.2 on 2025-04-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_usercountry_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercountry",
            name="currency",
        ),
    ]
