# Generated by Django 5.1.6 on 2025-02-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_rates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="country_type",
            field=models.CharField(
                choices=[("DEPARTURE", "Departure"), ("DESTINATION", "Destination")],
                default="DESTINATION",
                max_length=12,
            ),
        ),
    ]
