# Generated by Django 5.1.6 on 2025-02-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_rates", "0003_alter_country_code_alter_country_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingzone",
            name="countries",
        ),
        migrations.AddField(
            model_name="shippingzone",
            name="departure_countries",
            field=models.ManyToManyField(
                limit_choices_to={"country_type": "DEPARTURE"},
                related_name="departure_zones",
                to="shipping_rates.country",
            ),
        ),
        migrations.AddField(
            model_name="shippingzone",
            name="destination_countries",
            field=models.ManyToManyField(
                limit_choices_to={"country_type": "DESTINATION"},
                related_name="destination_zones",
                to="shipping_rates.country",
            ),
        ),
    ]
