# Generated by Django 5.1.6 on 2025-02-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_rates", "0004_remove_shippingzone_countries_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="country",
            constraint=models.UniqueConstraint(
                fields=("code", "country_type"), name="unique_country_code_type"
            ),
        ),
    ]
