# Generated by Django 5.1.6 on 2025-02-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_rates", "0005_country_unique_country_code_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetype",
            name="price",
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
