# Generated by Django 5.1.6 on 2025-03-05 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_rates", "0007_alter_additionalcharge_zones"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="additionalcharge",
            options={
                "ordering": ["name"],
                "verbose_name": "Additional Charge",
                "verbose_name_plural": "Additional Charges",
            },
        ),
        migrations.AddField(
            model_name="additionalcharge",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="additionalcharge",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="additionalcharge",
            name="charge_type",
            field=models.CharField(
                choices=[
                    ("FIXED", "Fixed Amount"),
                    ("PERCENTAGE", "Percentage of Base Cost"),
                ],
                default="FIXED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="additionalcharge",
            name="service_types",
            field=models.ManyToManyField(
                related_name="additional_charges", to="shipping_rates.servicetype"
            ),
        ),
        migrations.AlterField(
            model_name="additionalcharge",
            name="zones",
            field=models.ManyToManyField(
                related_name="additional_charges", to="shipping_rates.shippingzone"
            ),
        ),
    ]
