# Generated by Django 5.1.6 on 2025-03-15 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_rates", "0009_extras"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weightbasedrate",
            old_name="base_rate",
            new_name="regulation_charge",
        ),
    ]
