# Generated by Django 5.1.6 on 2025-03-15 08:12

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_rates", "0010_rename_base_rate_weightbasedrate_regulation_charge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extras",
            name="price",
        ),
        migrations.AddField(
            model_name="extras",
            name="charge_type",
            field=models.CharField(
                choices=[
                    ("FIXED", "Fixed Amount"),
                    ("PERCENTAGE", "Percentage of Base Cost"),
                ],
                default="FIXED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="extras",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="extras",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="extras",
            name="value",
            field=models.DecimalField(
                decimal_places=2,
                default=23,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
    ]
