# Generated by Django 5.0.2 on 2025-03-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_rates", "0011_remove_extras_price_extras_charge_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Conversion rate relative to MYR (Malaysian Ringgit)",
                        max_digits=12,
                    ),
                ),
            ],
        ),
    ]
