# Generated by Django 5.0.2 on 2025-03-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_rates", "0012_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weightbasedrate",
            name="regulation_charge",
        ),
    ]
