# Generated by Django 5.0.2 on 2025-04-04 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_rates", "0013_remove_weightbasedrate_regulation_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shipping_rates.currency",
            ),
        ),
    ]
