# Generated by Django 5.0.2 on 2025-04-07 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_rates", "0014_country_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicetype",
            name="price",
        ),
    ]
