# Generated by Django 5.0.2 on 2025-04-09 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_rates", "0015_remove_servicetype_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicRate",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=12, primary_key=True, serialize=False
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("INSURANCE", "Insurance"),
                            ("BUY4ME_FEE", "Buy4Me Fee"),
                            ("OTHER", "Other"),
                        ],
                        default="INSURANCE",
                        max_length=100,
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed Amount"),
                            ("PERCENTAGE", "Percentage of Base Cost"),
                        ],
                        default="FIXED",
                        max_length=100,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
