# Generated by Django 5.0.2 on 2025-04-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_rates", "0016_dynamicrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dynamicrate",
            name="rate_type",
            field=models.CharField(
                choices=[
                    ("COD_FEE", "COD Fee"),
                    ("BUY4ME_FEE", "Buy4Me Fee"),
                    ("OTHER", "Other"),
                ],
                default="COD_FEE",
                max_length=100,
            ),
        ),
    ]
