# Generated by Django 5.0.2 on 2025-04-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_rates", "0017_alter_dynamicrate_rate_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extras",
            name="value",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
